# Generated by Django 5.0.4 on 2024-12-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('model_version', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('model_year', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('battery_capacity_kwh', models.IntegerField()),
            ],
            options={
                'db_table': 'electric_cars',
                'ordering': ('make', 'model', 'model_version', 'model_year', 'battery_capacity_kwh'),
            },
        ),
    ]
