# Generated by Django 5.0.4 on 2024-05-31 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('external', '0001_initial'),
        ('netzentgelte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'devices_manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='addresses', to='netzentgelte.zipcode')),
            ],
            options={
                'db_table': 'devices_addresses',
            },
        ),
        migrations.CreateModel(
            name='DummyHeatPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('some_config_value', models.CharField(max_length=255)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s', to='external.apikey')),
            ],
            options={
                'db_table': 'devices_dummy_heat_pumps',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('manual_mode', models.BooleanField(default=False)),
                ('time_profile_active', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='devices', to='devices.address')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='devices', to='devices.manufacturer')),
            ],
            options={
                'db_table': 'devices_devices',
            },
        ),
        migrations.CreateModel(
            name='SmartthingsHeatPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('smartthings_device_id', models.CharField(max_length=511)),
                ('module_name', models.CharField(choices=[('main', 'Water'), ('INDOOR', 'Heating')], max_length=255)),
                ('default_flow_temperature', models.IntegerField()),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s', to='external.apikey')),
            ],
            options={
                'db_table': 'devices_smartthings_heat_pumps',
            },
        ),
        migrations.CreateModel(
            name='TimeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_profiles', to='devices.device')),
            ],
            options={
                'db_table': 'devices_time_profiles',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('time_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='devices.timeprofile')),
            ],
            options={
                'db_table': 'devices_time_slots',
            },
        ),
        migrations.CreateModel(
            name='TimeSlotTargetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow_temperature', models.IntegerField()),
                ('netzentgelt_magnitude', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='time_slot_target_values', to='netzentgelte.magnitude')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_values', to='devices.timeslot')),
            ],
            options={
                'db_table': 'devices_time_slot_target_values',
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['content_type', 'object_id'], name='devices_dev_content_fb146e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslottargetvalue',
            unique_together={('time_slot', 'netzentgelt_magnitude')},
        ),
    ]
