# Generated by Django 5.0.4 on 2024-05-10 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('devices', '0001_initial'),
        ('execution_conditions', '0001_initial'),
        ('external', '0001_initial'),
        ('netzentgelte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionexecutioncondition',
            name='execution_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_execution_conditions', to='execution_conditions.executioncondition'),
        ),
        migrations.AddField(
            model_name='action',
            name='execution_conditions',
            field=models.ManyToManyField(related_name='actions', through='devices.ActionExecutionCondition', to='execution_conditions.executioncondition'),
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='addresses', to='netzentgelte.zipcode'),
        ),
        migrations.AddField(
            model_name='command',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='commands', to='devices.action'),
        ),
        migrations.AddField(
            model_name='commandlog',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.command'),
        ),
        migrations.AddField(
            model_name='commandlog',
            name='failed_execution_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_command_logs', to='execution_conditions.executioncondition'),
        ),
        migrations.AddField(
            model_name='device',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='devices', to='devices.address'),
        ),
        migrations.AddField(
            model_name='device',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='devices.device'),
        ),
        migrations.AddField(
            model_name='deviceexecutioncondition',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices_execution_conditions', to='devices.device'),
        ),
        migrations.AddField(
            model_name='deviceexecutioncondition',
            name='execution_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices_execution_conditions', to='execution_conditions.executioncondition'),
        ),
        migrations.AddField(
            model_name='device',
            name='execution_conditions',
            field=models.ManyToManyField(related_name='devices', through='devices.DeviceExecutionCondition', to='execution_conditions.executioncondition'),
        ),
        migrations.AddField(
            model_name='dummyheatpump',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s', to='external.apikey'),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='devices', to='devices.manufacturer'),
        ),
        migrations.AddField(
            model_name='smartthingsheatpump',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s', to='external.apikey'),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('device', 'type')},
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['content_type', 'object_id'], name='devices_dev_content_fb146e_idx'),
        ),
    ]
