# Generated by Django 5.0.4 on 2024-05-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('turn_on', 'Turn On'), ('turn_off', 'Turn Off'), ('set_flow_temperature', 'Set Flow Temperature')], max_length=255),
        ),
    ]
