# Generated by Django 5.0.4 on 2024-05-07 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
        ('external', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyHeatPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('some_config_value', models.CharField(max_length=255)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s', to='external.api')),
            ],
            options={
                'db_table': 'devices_dummy_heat_pumps',
            },
        ),
    ]
