# Generated by Django 5.0.4 on 2024-05-08 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_action_type'),
        ('external', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartthingsHeatPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('smartthings_device_id', models.CharField(max_length=511)),
                ('module_name_water', models.CharField(max_length=255)),
                ('module_name_heating', models.CharField(max_length=255)),
                ('default_flow_temperature_water', models.IntegerField()),
                ('default_flow_temperature_heating', models.IntegerField()),
                ('api_config', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s', to='external.apiconfig')),
            ],
            options={
                'db_table': 'devices_smartthings_heat_pumps',
            },
        ),
    ]
