# Generated by Django 5.0.4 on 2024-05-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_dummyheatpump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='parameters',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('device', 'type')},
        ),
    ]
