# Generated by Django 5.0.4 on 2024-12-01 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electric_cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'electricity_rates_network_operators',
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zip_code', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'electricity_rates_zip_codes',
            },
        ),
        migrations.CreateModel(
            name='GridFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grid_fee_per_kilowatt_hour_cents', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basic_grid_fee_yearly_euro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
                ('network_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_fees', to='electricity_rates.networkoperator')),
            ],
            options={
                'db_table': 'electricity_rates_grid_fees',
            },
        ),
        migrations.CreateModel(
            name='BasicInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kilowatt_hour_rate_static', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('basic_fee_monthly_static', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('kilowatt_hours_last_year_static', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('electric_car', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='basic_inputs', to='electric_cars.car')),
                ('network_operator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='basic_inputs', to='electricity_rates.networkoperator')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='basic_inputs', to='electricity_rates.zipcode')),
            ],
            options={
                'db_table': 'electricity_rates_basic_inputs',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('electricity_costs_last_year_static', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True)),
                ('electricity_costs_last_year_dynamic', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True)),
                ('basic_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='electricity_rates.basicinput')),
            ],
            options={
                'db_table': 'electricity_rates_results',
            },
        ),
        migrations.CreateModel(
            name='NetworkOperatorZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_operators_zip_codes_operators', to='electricity_rates.networkoperator')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='network_operators_zip_codes_codes', to='electricity_rates.zipcode')),
            ],
            options={
                'db_table': 'electricity_rates_network_operators_zip_codes',
                'unique_together': {('network_operator', 'zip_code')},
            },
        ),
        migrations.AddField(
            model_name='networkoperator',
            name='zip_codes',
            field=models.ManyToManyField(related_name='network_operators', through='electricity_rates.NetworkOperatorZipCode', to='electricity_rates.zipcode'),
        ),
    ]
