# Generated by Django 5.0.4 on 2024-12-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinput',
            name='battery_exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicinput',
            name='electric_car_charging_with_solar_power',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicinput',
            name='solar_system_exists',
            field=models.BooleanField(default=False),
        ),
    ]
