# Generated by Django 5.0.4 on 2024-11-30 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grid_fee_per_kilowatt_hour_cents', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basic_grid_fee_yearly_euro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
                ('network_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_fees', to='electricity_rates.networkoperator')),
            ],
            options={
                'db_table': 'electricity_rates_grid_fees',
            },
        ),
    ]
