# Generated by Django 5.0.4 on 2024-12-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinput',
            name='electric_car_charging_frequency',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='basicinput',
            name='electric_car_charging_weekdays',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
