# Generated by Django 5.0.4 on 2024-11-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinput',
            name='electric_car',
            field=models.BooleanField(default=False),
        ),
    ]
