# Generated by Django 5.0.4 on 2024-11-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_rates', '0002_basicinput_electric_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinput',
            name='electric_car_kilowatt_hours',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=20, null=True),
        ),
    ]
