services:
  postgres:
    image: postgres:16.2
    env_file:
      - .env-docker
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.14-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./.docker/redis/data:/var/lib/redis/data

  django:
    image: ghcr.io/mathis1993/griddy:latest
    env_file:
      - .env-docker
    ports:
      - '8000:8000'
