# Generated by Django 5.0.4 on 2024-05-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_conditions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummySwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'execution_conditions_dummy_switches',
            },
        ),
    ]
