# Generated by Django 5.0.4 on 2024-05-29 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magnitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('magnitude', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=255)),
            ],
            options={
                'db_table': 'netzentgelte_magnitudes',
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'netzentgelte_zip_codes',
            },
        ),
        migrations.CreateModel(
            name='Netzentgelt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.FloatField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('magnitude', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='netzentgelte', to='netzentgelte.magnitude')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='netzentgelte', to='netzentgelte.zipcode')),
            ],
            options={
                'db_table': 'netzentgelte_netzentgelte',
            },
        ),
    ]
